--DDL QUERIES

--CREATING A TABLE
CREATE TABLE PromoCode (
    promo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(20) UNIQUE NOT NULL,
    discount_percent NUMBER(5,2) CHECK (discount_percent BETWEEN 0 AND 100),
    expiry_date DATE
);
--ADD A COLUMN
ALTER TABLE Vehicle ADD vehicle_type VARCHAR2(30);
--MODIFY A COLUMN
ALTER TABLE Vehicle MODIFY color VARCHAR2(25);
--DROP A COLUMN
ALTER TABLE Vehicle DROP COLUMN vehicle_type;
--RENAME A COLUMN
ALTER TABLE Vehicle RENAME COLUMN model TO vehicle_model;
--TRUNCATE A TABLE
INSERT INTO PromoCode (code, discount_percent, expiry_date)
VALUES ('UBER50', 50, TO_DATE('2025-12-31', 'YYYY-MM-DD'));
TRUNCATE TABLE PromoCode;
--DROP A TABLE 
DROP TABLE IF EXISTS PromoCode;

--CONSTRAINTS

--ADD A CONSTRAINT
ALTER TABLE Ride
ADD CONSTRAINT chk_positive_fare CHECK (fare >= 0);
--RENAME A CONSTRAINT
ALTER TABLE Ride RENAME CONSTRAINT chk_positive_fare TO chk_pos_fare;
--DROP A CONSTRAINT
ALTER TABLE Ride DROP CONSTRAINT chk_pos_fare;

--DML QUERIES 

--UPDATE

--UPDATING A SPECIFIC RIDE'S FARE
UPDATE Ride
SET fare = 400.00
WHERE ride_id = 1;
--UPDATING A USER'S PASSWORD
UPDATE UserAccount
SET PASSWORD = '345278'
WHERE FNAME LIKE 'A%';

--DELETE 

-- Delete a canceled ride
DELETE FROM Ride
WHERE status = 'Cancelled';
-- Delete a driver record 
DELETE FROM Driver
WHERE driver_id = 2;


--DEFAULT VALUES

ALTER TABLE RideType MODIFY base_fare DEFAULT 50.00;
INSERT INTO RideType (type_name, per_km_rate)
VALUES ('Uber Auto',12);

--MULTI-TABLE INSERTS

INSERT ALL
    INTO UserAccount (user_id, fname, lname, password, phone_no, email)
    VALUES (10, 'Sia', 'Das','sia000',  '9823456789', 'sia@gmail.com')

    INTO Ride (ride_id, cust_id, pickup_location_id, drop_location_id, fare, status)
    VALUES (11, 9, 3,4, 255, 'Completed')
SELECT * FROM dual;

--INSERT INTO ... SELECT
CREATE TABLE PaymentSummary (
    ride_id NUMBER,
    amount NUMBER(8,2),
    payment_method VARCHAR2(20)
);
INSERT INTO PaymentSummary (ride_id, amount, payment_method)
SELECT ride_id, amount, payment_method
FROM Payment
WHERE payment_status = 'Completed';

--SELECT AND WHERE 

--Selecting Columns
SELECT * FROM UserAccount;
SELECT ride_id, fare, status FROM Ride;
-- Find completed rides
SELECT *
FROM Ride
WHERE status = 'Completed';

--USING ALIASES
SELECT fname AS "Customer Name", email AS "Customer Email"
FROM UserAccount
WHERE ROLE = 'CUSTOMER';

--LIMITING ROWS

-- Show top 5 highest fares
SELECT * FROM Ride
ORDER BY fare DESC
FETCH FIRST 3 ROWS ONLY;

--COMPARISON OPERATORS 

-- Rides costing more than ₹300
SELECT * FROM Ride
WHERE fare > 300;

-- Drivers with license starting with 'WB'
SELECT * FROM Driver
WHERE license_no LIKE 'WB%';

-- Rides with fare between ₹200 and ₹500
SELECT ride_id, fare
FROM Ride
WHERE fare BETWEEN 200 AND 500;

-- Rides that are either completed or payment is pending
SELECT *
FROM Ride
WHERE status = 'Completed' OR status = 'Pending';

--Concatenation
SELECT fname || ' ' || lname AS "FULL NAME" FROM UserAccount;


--SINGLE ROW FUNCTIONS

-- Convert all customer names to uppercase
SELECT UPPER(fname) AS "Uppercase Name" FROM UserAccount;

-- Find length of each user’s name
SELECT fname, LENGTH(fname) AS "Name Length" FROM UserAccount;

-- Display customer name with phone number
SELECT CONCAT(fname, phone_no) AS "Name and Phone"
FROM UserAccount;

-- Show first 3 letters of each customer’s name
SELECT SUBSTR(fname, 1, 3) AS "Short Name"
FROM UserAccount;

--GROUP FUNCTIONS 

-- Total number of rides
SELECT COUNT(*) AS "Total Rides" FROM Ride;

-- Average fare of all rides
SELECT AVG(fare) AS "Average Fare" FROM Ride;

-- Highest and lowest fare
SELECT MAX(fare) AS "Max Fare", MIN(fare) AS "Min Fare" FROM Ride;

-- Total amount earned by drivers
SELECT SUM(fare) AS "Total Earnings" FROM Ride;

--DISTINCT 

-- Count unique customers who have taken rides
SELECT COUNT(DISTINCT cust_id) AS "Unique Customers"
FROM Ride;

-- List all unique pickup locations
SELECT DISTINCT pickup_location_id FROM Ride;

--GROUP BY 
-- Total rides taken by each customer
SELECT cust_id, COUNT(*) AS "Number of Rides"
FROM Ride
GROUP BY cust_id;

-- Average fare per driver
SELECT driver_id, AVG(fare) AS "Average Fare"
FROM Ride
GROUP BY driver_id;

-- Total fare per ride status
SELECT status, SUM(fare) AS "Total Fare"
FROM Ride
GROUP BY status;

--HAVING

-- Show drivers who earned more than ₹500 in total
SELECT driver_id, SUM(fare) AS "Total Fare"
FROM Ride
GROUP BY driver_id
HAVING SUM(fare) > 500;

-- Customers who took more than 1 ride
SELECT cust_id, COUNT(*) AS "Total Rides"
FROM Ride
GROUP BY cust_id
HAVING COUNT(*) > 1;

-- Ride status groups with average fare above ₹300
SELECT status, AVG(fare) AS "Avg Fare"
FROM Ride
GROUP BY status
HAVING AVG(fare) > 300;

-- Customers with completed rides above ₹400
SELECT cust_id, COUNT(*) AS "High Fare Rides"
FROM Ride
WHERE status = 'Completed' AND fare > 400
GROUP BY cust_id
HAVING COUNT(*) >= 1
ORDER BY COUNT(*) DESC;

--JOINS 

--CROSS JOIN
-- Show all combinations of drivers and vehicles
SELECT d.driver_id, v.vehicle_id, v.vehicle_model
FROM Driver d
CROSS JOIN Vehicle v;

-- Example use case: find all possible driver-location combinations
SELECT d.driver_id, l.city
FROM Driver d
CROSS JOIN Location l;

--NATURAL JOIN
-- Join Ride and Driver where they share driver_id
SELECT ride_id, driver_id, status, fare, rating
FROM Ride
NATURAL JOIN Driver;

-- Join Ride and Customer (cust_id common)
SELECT ride_id, cust_id, fare, status
FROM Ride
NATURAL JOIN Customer;

--INNER JOIN

--CUSTOMER NAMES
SELECT cust_id, fname
FROM CUSTOMER
INNER JOIN USERACCOUNT
ON CUST_ID = USER_ID;

-- Show rides with driver names and fare
SELECT r.ride_id, d.driver_id, r.fare, r.status
FROM Ride r
INNER JOIN Driver d ON r.driver_id = d.driver_id;

-- Show vehicle details for each driver
SELECT d.driver_id, v.vehicle_model, v.license_plate
FROM Driver d
INNER JOIN Vehicle v ON d.driver_id = v.driver_id;

--SELF JOIN

-- Find drivers who are in the same city (using Location)
SELECT d1.driver_id AS Driver1, d2.driver_id AS Driver2, l.city
FROM Driver d1
JOIN Driver d2 ON d1.location_id = d2.location_id
JOIN Location l ON d1.location_id = l.location_id
WHERE d1.driver_id < d2.driver_id;

-- Show rides with same pickup and drop location
SELECT r1.ride_id AS Ride1, r2.ride_id AS Ride2, r1.pickup_location_id
FROM Ride r1
JOIN Ride r2 ON r1.pickup_location_id = r2.pickup_location_id
WHERE r1.ride_id < r2.ride_id;

--EQUI JOIN
-- Show ride and driver details using = condition
SELECT r.ride_id, d.driver_id, d.rating, r.fare
FROM Ride r, Driver d
WHERE r.driver_id = d.driver_id;

-- Customer and ride details (older style join)
SELECT c.cust_id, r.ride_id, r.status, r.fare
FROM Customer c, Ride r
WHERE c.cust_id = r.cust_id;


--NON EQUI JOIN 
-- Match rides with ride type based on fare range
SELECT r.ride_id, r.fare, rt.type_name
FROM Ride r
JOIN RideType rt
ON r.fare BETWEEN rt.base_fare AND (rt.base_fare + 5 * rt.per_km_rate);

-- Drivers categorized by rating range (example thresholds)
SELECT d.driver_id, d.rating, rt.type_name
FROM Driver d
JOIN RideType rt
ON d.rating BETWEEN 3 AND 5;

--LEFT OUTER JOIN
-- Show all customers even if they haven’t taken a ride
SELECT c.cust_id, r.ride_id, r.status
FROM Customer c
LEFT OUTER JOIN Ride r ON c.cust_id = r.cust_id;

-- Show all drivers and any rides assigned
SELECT d.driver_id, r.ride_id, r.status
FROM Driver d
LEFT OUTER JOIN Ride r ON d.driver_id = r.driver_id;

--RIGHT OUTER JOIN
-- Show all rides and their driver info (if any)
SELECT r.ride_id, d.driver_id, d.rating
FROM Ride r
RIGHT OUTER JOIN Driver d ON r.driver_id = d.driver_id;

-- Show all locations and any driver currently at them
SELECT l.city, d.driver_id
FROM Location l
RIGHT OUTER JOIN Driver d ON l.location_id = d.location_id;

--FULL OUTER JOIN
-- Show all rides and all drivers (even if no match)
SELECT r.ride_id, d.driver_id, r.status, d.rating
FROM Ride r
FULL OUTER JOIN Driver d ON r.driver_id = d.driver_id;

-- All customers and drivers by location (even if missing)
SELECT c.cust_id, d.driver_id, l.city
FROM Customer c
FULL OUTER JOIN Driver d ON c.location_id = d.location_id
FULL OUTER JOIN Location l ON l.location_id = d.location_id;

-- Completed rides with driver name, customer name, fare and payment status
SELECT r.ride_id, d.driver_id,ud.fname as "driver", c.cust_id, uc.fname as "customer", r.fare, p.payment_status
FROM Ride r
JOIN Driver d ON r.driver_id = d.driver_id
INNER JOIN UserAccount ud ON r.driver_id = ud.user_id 
JOIN Customer c ON r.cust_id = c.cust_id
INNER JOIN UserAccount uc ON r.cust_id = uc.user_id
LEFT JOIN Payment p ON r.ride_id = p.ride_id
WHERE r.status = 'Completed'
ORDER BY r.fare DESC;


--SUBQUERIES

--Find rides that cost more than the average fare
SELECT ride_id, fare
FROM Ride
WHERE fare > (SELECT AVG(fare) FROM Ride);

-- Find customers who have taken at least one ride
SELECT fname, lname
FROM UserAccount
WHERE user_id IN (SELECT cust_id FROM Ride);

-- List driver details for the most expensive ride
SELECT driver_id, rating
FROM Driver
WHERE driver_id = (
    SELECT driver_id
    FROM Ride
    WHERE fare = (SELECT MAX(fare) FROM Ride)
);

--Find the driver who has the highest rating
SELECT fname, lname, rating
FROM Driver
JOIN UserAccount ON driver.driver_id = useraccount.user_id
WHERE rating = (SELECT MAX(rating) FROM Driver);

--Find rides costlier than the average completed ride
SELECT ride_id, fare
FROM Ride
WHERE fare > (
    SELECT AVG(fare)
    FROM Ride
    WHERE status = 'Completed'
);

--Find the location of the top-rated driver
SELECT city, state
FROM Location
WHERE location_id = (
    SELECT location_id
    FROM Driver
    WHERE rating = (SELECT MAX(rating) FROM Driver)
);

--Find rides with fares equal to the minimum fares of any ride type
SELECT ride_id, fare
FROM Ride
WHERE fare IN (
    SELECT MIN(fare)
    FROM Ride
    GROUP BY type_id
);

--Find drivers who have not yet completed any ride
SELECT driver_id, rating
FROM Driver
WHERE driver_id NOT IN (
    SELECT driver_id
    FROM Ride
    WHERE status = 'Completed'
);

--CORRELATED SUBQUERIES

--Find rides with fares greater than the average fare of the same ride type
SELECT r.ride_id, r.fare, r.type_id
FROM Ride r
WHERE fare > (
    SELECT AVG(fare)
    FROM Ride
    WHERE type_id = r.type_id
);

--Find drivers whose rating is above the average rating of their city
SELECT d.driver_id, d.rating
FROM Driver d
WHERE d.rating > (
    SELECT AVG(d2.rating)
    FROM Driver d2
    WHERE d2.location_id = d.location_id
);

--VIEWS 

--CREATING VIEWS

--VIEW FOR COMPLETED RIDES
CREATE VIEW CompletedRides AS
SELECT r.ride_id, c.cust_id, d.driver_id, r.fare, r.status
FROM Ride r
JOIN Customer c ON r.cust_id = c.cust_id
JOIN Driver d ON r.driver_id = d.driver_id
WHERE r.status = 'Completed';

SELECT * FROM CompletedRides;

--View showing driver details with vehicle info
CREATE VIEW DriverVehicleInfo AS
SELECT d.driver_id, ua.fname, ua.lname, v.vehicle_model, v.license_plate, d.rating
FROM Driver d
JOIN Vehicle v ON d.driver_id = v.driver_id
JOIN UserAccount ua ON d.driver_id = ua.user_id;

SELECT * FROM DriverVehicleInfo;

-- Create a simple updatable view
CREATE VIEW SimpleCustomerView AS
SELECT user_id, fname, lname, phone_no
FROM UserAccount
WHERE role = 'CUSTOMER';

-- Insert a new record using the view
INSERT INTO SimpleCustomerView (fname, lname, phone_no)
VALUES ('Anany', 'Singal', '9111877726');

--UPDATE through a view
UPDATE SimpleCustomerView
SET phone_no = '9876543211'
WHERE fname = 'Ananya';

--DELETE through a view
DELETE FROM SimpleCustomerView
WHERE fname = 'Ananya';

--Creating a read-only view
CREATE VIEW RideSummaryView AS
SELECT driver_id, COUNT(ride_id) AS total_rides, AVG(fare) AS avg_fare
FROM Ride
GROUP BY driver_id
WITH READ ONLY;

--Modify (replace) a view
CREATE OR REPLACE VIEW CompletedRides AS
SELECT r.ride_id, c.cust_id, d.driver_id, r.fare, r.status, r.pickup_time, r.dropoff_time
FROM Ride r
JOIN Customer c ON r.cust_id = c.cust_id
JOIN Driver d ON r.driver_id = d.driver_id
WHERE r.status = 'Completed';

--Drop a view
DROP VIEW SimpleCustomerView;

--Check all views created by current user
SELECT view_name FROM user_views;

--TCL

--ROLLBACK AND SAVEPOINT

BEGIN
    INSERT INTO USERACCOUNT (Fname, LNAME, PHONE_NO, email, ROLE)
    VALUES ('Test', 'User', '9999999999', 'test@mail.com', 'CUSTOMER');

    SAVEPOINT sp1;

    UPDATE USERACCOUNT
    SET email = 'test_updated@mail.com'
    WHERE fname = 'Test';

    ROLLBACK TO sp1;

    COMMIT;
END;
/


-- Table to log actions
CREATE TABLE customer_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    action_desc VARCHAR2(100)
);

-- Trigger
CREATE OR REPLACE TRIGGER trg_customer_insert
AFTER INSERT ON customer
FOR EACH ROW
BEGIN
    INSERT INTO customer_log (action_desc)
    VALUES ('New customer inserted with ID: ' || :NEW.cust_id);
END;
/

--STORED PROCEDURE 
CREATE OR REPLACE PROCEDURE add_promo_code (
    p_code IN VARCHAR2,
    p_discount IN NUMBER,
    p_expiry IN DATE
)
IS
BEGIN
    INSERT INTO PromoCode (code, discount_percent, expiry_date)
    VALUES (p_code, p_discount, p_expiry);

    DBMS_OUTPUT.PUT_LINE('Promo code ' || p_code || ' added successfully!');
END;
/
BEGIN
    add_promo_code('DIWALI50', 50, TO_DATE('2025-12-31', 'YYYY-MM-DD'));
END;
/

--TRANSACTION

BEGIN
    -- Insert a record
    INSERT INTO Location (address, city, state, pincode)
    VALUES ('MG Road', 'Bangalore', 'Karnataka', '560001');

    SAVEPOINT sp1;  -- mark a savepoint

    INSERT INTO Location (address, city, state, pincode)
    VALUES ('Connaught Place', 'Delhi', 'Delhi', '110001');

    -- Oops! Let’s roll back to the first insert
    ROLLBACK TO sp1;

    -- Insert something else after rollback
    INSERT INTO Location (address, city, state, pincode)
    VALUES ('Park Street', 'Kolkata', 'West Bengal', '700016');

    COMMIT;  -- finalize all successful inserts
END;
/
