-- USER ACCOUNT TABLE

CREATE TABLE UserAccount (
   user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   fname VARCHAR2(50) NOT NULL,
   lname VARCHAR2(50) NOT NULL,
   password VARCHAR2(25) NOT NULL,
   phone_no VARCHAR2(15) UNIQUE NOT NULL,
   email VARCHAR2(100) UNIQUE,
   role VARCHAR2(10) CHECK (role IN ('DRIVER', 'CUSTOMER'))
);

-- LOCATION TABLE

CREATE TABLE Location (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR2(100),
    city VARCHAR2(50),
    state VARCHAR2(50),
    pincode VARCHAR2(10)
);

-- CUSTOMER TABLE

CREATE TABLE Customer (
    cust_id NUMBER PRIMARY KEY,
    location_id NUMBER REFERENCES Location(location_id),
    FOREIGN KEY (cust_id) REFERENCES UserAccount(user_id) ON DELETE CASCADE
);

-- DRIVER TABLE

CREATE TABLE Driver (
    driver_id NUMBER PRIMARY KEY,
    license_no VARCHAR2(30) UNIQUE NOT NULL,
    rating NUMBER(2,1),
    location_id NUMBER REFERENCES Location(location_id),
    FOREIGN KEY (driver_id) REFERENCES UserAccount(user_id) ON DELETE CASCADE
);

-- VEHICLE TABLE

CREATE TABLE Vehicle (
    vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id NUMBER NOT NULL REFERENCES Driver(driver_id),
    model VARCHAR2(50),
    license_plate VARCHAR2(20) UNIQUE NOT NULL,
    color VARCHAR2(20) NOT NULL,
    capacity NUMBER(2) NOT NULL,
    insurance_no VARCHAR2(30) NOT NULL,
    insurance_provider VARCHAR2(50),
    insurance_expiry DATE 
);

-- RIDE TYPE TABLE

CREATE TABLE RideType (
    type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR2(20) UNIQUE NOT NULL,
    base_fare NUMBER(8,2),
    per_km_rate NUMBER(8,2)
);

-- RIDE TABLE

CREATE TABLE Ride (
    ride_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id NUMBER REFERENCES Driver(driver_id),
    cust_id NUMBER REFERENCES Customer(cust_id),
    pickup_location_id NUMBER REFERENCES Location(location_id),
    drop_location_id NUMBER REFERENCES Location(location_id),
    driver_arrived_at TIMESTAMP,
    pickup_time TIMESTAMP,
    dropoff_time TIMESTAMP,
    status VARCHAR2(20) CHECK (status IN ('Scheduled', 'Ongoing', 'Completed', 'Cancelled')),
    fare NUMBER(8,2) CHECK (fare >= 0),
    type_id NUMBER REFERENCES RideType(type_id)
);

-- PAYMENT TABLE

CREATE TABLE Payment (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id NUMBER NOT NULL REFERENCES Ride(ride_id),
    amount NUMBER(8,2) NOT NULL,
    payment_method VARCHAR2(20) CHECK (payment_method IN ('Cash', 'Card', 'Wallet', 'UPI')),
    payment_status VARCHAR2(20) CHECK (payment_status IN ('Pending', 'Completed', 'Failed')),
    payment_time TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- RATING TABLE

CREATE TABLE Rating (
    ride_id NUMBER PRIMARY KEY REFERENCES Ride(ride_id) ON DELETE CASCADE,
    rating NUMBER(2,1) CHECK (rating BETWEEN 1 AND 5),
    comments VARCHAR2(200)
);